spring.application.name=SpringAiProject

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1

spring.ai.openai.chat.model=llama3-70b-8192
spring.ai.openai.chat.temperature=0.7